auto: true
server: true
permalink: none
baseurl: /notes
exclude:
- .gitignore
- README.md

prose:
  rooturl: "_posts"
  metadata: 
    _posts/articles:
      published: false
      layout: article
      title: Post Title
      abstract: Short summary of article.
      author_twitter: digitisation
      author: Oliver Scott
      categories:
      - articles
    _posts/projects:
      published: false
      layout: about
      title: Post Title
      abstract: Short summary of article.
      name: "Project Name"
      img:  "Project Thumbnail"
      categories:
      - projects